openapi: "3.0.1"
info:
  title: "ProductApi"
  version: "2023-11-19 14:53:38UTC"
servers:
- url: "https://um54zkzc6i.execute-api.us-east-1.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: ""
paths:
  /products:
    get:
      summary: Get list of products
      description:
        Returns full array of products
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{productId}:
    get:
      summary: Get product by ID
      description:
        Returns a single product
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Product'
        '204':
          description: Product not found
    parameters:
    - name: "productId"
      in: "path"
      description: "Generated path parameter for productId"
      required: true
      schema:
        type: "string"
components:
  schemas:
    Product:
      required:
        - name
        - photoUrls
      type: object
      properties:
        count:
          type: integer
          example: 7
        id:
          type: string
          example: 7567ec4b-b10c-48c5-9345-fc73c48a80a2
        description:
          type: string
          example: Short Product Description2
        price:
          type: number
          example: 23.5
        title:
          type: string
          example: ProductTop
      xml:
        name: product
x-amazon-apigateway-cors:
  allowMethods:
  - "*"
  allowHeaders:
  - "*"
  maxAge: -42
  allowCredentials: false
  allowOrigins:
  - "*"
x-amazon-apigateway-importexport-version: "1.0"